// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pomodoro.DAL;

#nullable disable

namespace Pomodoro.DAL.Migrations
{
    [DbContext(typeof(PomodoroDbContext))]
    [Migration("20261006143549_add-UserProfileAndPomodoroSettings")]
    partial class addUserProfileAndPomodoroSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pomodoro.DAL.PomodoroSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountPomodoroBeforeLongBreak")
                        .HasColumnType("int");

                    b.Property<int>("LongBreak")
                        .HasColumnType("int");

                    b.Property<int>("PomodoroDuration")
                        .HasColumnType("int");

                    b.Property<int>("ShortBreak")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("PomodoroSettings");
                });

            modelBuilder.Entity("Pomodoro.DAL.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCompletePomodoros")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("Pomodoro.DAL.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Pomodoro.DAL.PomodoroSettings", b =>
                {
                    b.HasOne("Pomodoro.DAL.UserProfile", "UserProfile")
                        .WithOne("Settings")
                        .HasForeignKey("Pomodoro.DAL.PomodoroSettings", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Pomodoro.DAL.Statistic", b =>
                {
                    b.HasOne("Pomodoro.DAL.UserProfile", "UserProfile")
                        .WithMany("Statistics")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Pomodoro.DAL.UserProfile", b =>
                {
                    b.Navigation("Settings");

                    b.Navigation("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
